max_epoch: 100
batch_size: 64
optimizer:
  name: "adam"
  kwargs:
    lr: 1e-4
    weight_decay: 0.00
criterion:
  name: "nll"
  kwargs:
    eps: 1e-8
patience: 50
stop_crit: "acc"
watch_freq: 100
metrics: {"genloss": 1, "acc": 1, "fid": 10, "viz": 10}
save: false
auto_stack: true
auto_unbind: false
