max_epoch: 4
batch_size: 64
optimizer:
  name: "adam"
  kwargs:
    lr: 1e-4
    weight_decay: 0.00
criterion:
  name: "generative-nll"  # User must implement and pass GenerativeNLL subclass
  kwargs:
    eps: 1e-8
patience: 10
stop_crit: "acc"
watch_freq: 1
metrics: {"genloss": 1, "acc": 1, "fid": 1, "viz": 1}
save: false
auto_stack: true
auto_unbind: false
