max_epoch: 4
batch_size: 256
optimizer:
  name: "adam"
  kwargs:
    lr: 1e-4
    weight_decay: 0.00
criterion:
  name: "nll"
  kwargs:
    eps: 1e-8
patience: 10
stop_crit: "genloss"
watch_freq: 1
metrics: {"genloss": 1}
save: false
auto_stack: true
auto_unbind: false
