backbone:
  architecture: mlp
  model_kwargs: {hidden_multipliers: [8.0, 8.0, 8.0, 8.0, 8.0], nonlinearity: LeakyReLU, negative_slope: 0.01}
head:
  class_aware: True
  architecture: linear
  model_kwargs: {}
discrimination:
  max_epoch_pre: 200
  max_epoch_gan: 20
  batch_size: 32
  optimizer:
    name: "adam"
    kwargs:
      lr: 1e-4
      weight_decay: 1e-6
  patience: 25
criterion:
  name: "wasserstein"
  kwargs: {"lamb": 25}
