defaults:
  - _self_ # has to be here such that overrides work
  - sampling: test
  - gantrain: test2
  - dataset: moons_4k
  - model/mps: d30D18
  - model/dis: wide_leaky_ens
  - pretrain/mps: adam_b64e500
  - pretrain/dis: adam_b64e1000lr3
  - wandb: defaults
  - reproduce/save: none
  - reproduce/random: "2811"
  - override hydra/job_logging: stream_only
  - override hydra/hydra_logging: none

hydra:
  run:
    # For single runs
    dir: outputs/${experiment}_${dataset.name}_${now:%d%b%y_%I%p%M} 

  sweep:
    # For multiruns
    dir: outputs/${experiment}_${dataset.name}_${now:%d%b%y}
    subdir: ${hydra.job.num}

  output_subdir: .hydra