experiment: default
descriptor: ""

defaults:
  - _self_ # has to be here such that overrides work
  - dataset: 2Dtoy/circles_2k
  - born: fourier/d4D3
  - trainer/classification: test
  - trainer/ganstyle: test
  - trainer/generative: null
  - trainer/adversarial: test
  - tracking: test
  - override hydra/job_logging: stream_only
  - override hydra/hydra_logging: none

hydra:
  run:
    # For single runs
    dir: outputs/${experiment}/${training_regime:}/${born.embedding}/d${born.init_kwargs.in_dim}D${born.init_kwargs.bond_dim}/${dataset.name}_${now:%d%m_%H%M}

  sweep:
    # For multiruns
    dir: outputs/${experiment}/${training_regime:}/${born.embedding}/d${born.init_kwargs.in_dim}D${born.init_kwargs.bond_dim}/${dataset.name}_${now:%d%m}
    subdir: ${hydra.job.num}

  output_subdir: .hydra