defaults:
  - _self_ # has to be here such that overrides work
  - dataset: circles_2k
  - born: d4D3
  - trainer/classification: test
  - trainer/ganstyle: test
  - trainer/adversarial: test
  - tracking: test
  - override hydra/job_logging: stream_only
  - override hydra/hydra_logging: none

hydra:
  run:
    # For single runs
    dir: outputs/${experiment}_${dataset.name}_${now:%d%b%y_%I%p%M} 

  sweep:
    # For multiruns
    dir: outputs/${experiment}_${dataset.name}_${now:%d%b%y}
    subdir: ${hydra.job.num}

  output_subdir: .hydra