project: gan_train # choose your own project name if you like
entity: martin-nissen-gonzalez-heidelberg-university # add here your wandb entity
mode: online # set to "online" to enable logging to wandb
seed: 42
random_state: 42
sampling:
  num_bins: 200
  num_spc: 1024
  batch_spc: 16
  method: secant
evasion: 
  method: "PGD"
  norm: 2
  criterion: 
    name: "negative log-likelihood"
    kwargs:
      eps: 1e-8
  strengths: [0.1] # not relative, default for dataspaces [0,1]^n\
